# Generated by Django 3.2.8 on 2022-06-23 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20220623_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 9, 29, 0, 395183)),
        ),
    ]
