# Generated by Django 3.2.8 on 2022-06-24 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_datetime_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 11, 38, 27, 472049)),
        ),
    ]
