# Generated by Django 3.2.8 on 2022-06-24 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_datetime_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='num_following',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 11, 39, 9, 576142)),
        ),
    ]
