# Generated by Django 3.2.8 on 2022-06-24 17:58

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20220624_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='_network_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 12, 58, 24, 98326)),
        ),
    ]
